### ISSUE TITLE
Bug: Freeze of coins does not work

### ISSUE THREAD

**Issue by HyperPeek** [kralverde/electrum-raven#6]
When freezing coins in the address dialogue they show up as frozen, but they are actually spent when trying to send.

**Comment by HyperPeek** [comment]
New behaviour in version:
Electrum version: 99ca78de6-dirty 
Python version: 3.8.5 (default, Jan 27 2021, 15:41:15) [GCC 9.3.0] 
Operating system: Linux-5.8.0-53-generic-x86_64-with-glibc2.29 

E | gui.qt.exception_window.Exception_Hook | exception caught by crash reporter
Traceback (most recent call last):
  File "/home/hatje/electrum-ravencoin-utd/electrum/gui/qt/address_list.py", line 264, in <lambda>
    menu.addAction(_("Freeze"), lambda: self.parent.set_frozen_state_of_addresses([addr], True))
  File "/home/hatje/electrum-ravencoin-utd/electrum/gui/qt/main_window.py", line 2165, in set_frozen_state_of_addresses
    self.utxo_list.update()
  File "/home/hatje/electrum-ravencoin-utd/electrum/gui/qt/utxo_list.py", line 89, in update
    amount = sum(x.value_sats() for x in coins)
TypeError: unsupported operand type(s) for +: 'int' and 'RavenValue'
